name: Publish to NPM registry

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        package:
          - eslint-config
          - prettier-config
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: ${{ github.repository || 'aenjojo/reusable-utilities' }}
          ref: ${{ github.ref || 'main' }}
      - name: Setup Node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org/'
          cache: yarn
          scope: '@aenjojo'
      - name: Install Dependencies
        run: yarn --immutable
      - name: Build All Packages
        working-directory: packages/${{ matrix.package }}
        run: yarn build
      - name: Publish
        working-directory: packages/${{ matrix.package }}
        run: |
          yarn config set npmAuthToken ${NODE_AUTH_TOKEN}
          yarn config set npmPublishRegistry "https://registry.npmjs.org/"
          
          yarn npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}